spring:
  application:
    name: condo-news
  data:
    mongodb:
      uri: mongodb://localhost:27017/condonews
      auto-index-creation: true

server:
  port: 8686
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:795351ff5bec966e4710d24ce22d6304}
  expiration: ${JWT_EXPIRATION:60000}
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:86400000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type,Accept,Origin,X-Requested-With
  exposed-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials,Authorization
  max-age: 3600

logging:
  level:
    br.com.gravitech.condonews: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO