spring:
  application:
    name: condo-news
  data:
    mongodb:
      uri: mongodb://localhost:27017/condonews

server:
  port: 8686
  servlet:
    context-path: /api

jwt:
  secret: secret
  expiration: 360000
  expiration-refresh: 86400000