spring:
  application:
    name: condo-news
  data:
    mongodb:
      uri: mongodb://localhost:27017/condonews

server:
  port: 8686
  servlet:
    context-path: /api

jwt:
  secret: 795351ff5bec966e4710d24ce22d6304
  expiration: 60000
  expiration-refresh: 86400000